### ISSUE TITLE
Adding libgraphviz-dev installation?

### ISSUE THREAD

**Issue by mhtb32** [kamiazya/setup-graphviz#86]
I tried installing `pygraphviz` which is a python wrapper for `graphviz`. I used this repository as a step in [my workflow](https://github.com/mhtb32/tl-env/blob/master/.github/workflows/build.yml#L26), but the installation of `pygraphviz` failed at this step:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/hostedtoolcache/Python/3.6.10/x64/include/python3.6m -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-3.6/pygraphviz/graphviz_wrap.o
  pygraphviz/graphviz_wrap.c:2987:10: fatal error: graphviz/cgraph.h: No such file or directory
   #include "graphviz/cgraph.h"
            ^~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
```

As suggested in [this issue](https://github.com/pygraphviz/pygraphviz/issues/163#issuecomment-570770201), I think the problem would be resolved by adding the installation of `libgraphviz-dev`.

**Comment by kamiazya** [comment]
@mhtb32 mhtb32 

Since we have created an [ts-graphviz organization](https://github.com/ts-graphviz), it was supported by the repository that was copied there.

https://github.com/ts-graphviz/setup-graphviz

Thank you.
